const primaryGreen = '#4CAF50';
const primaryGreenLight = '#8BC34A';
const primaryGreenDark = '#2E7D32';
const accentColor = '#1E88E5';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: primaryGreen,
    tabIconDefault: '#ccc',
    tabIconSelected: primaryGreen,
    primary: primaryGreen,
    primaryLight: primaryGreenLight,
    secondary: '#F5F8FA',
    secondaryLight: '#EDF2F7',
    accent: accentColor,
    success: '#4CD964',
    error: '#FF3B30',
    warning: '#FFCC00',
    border: '#E1E1E1',
    textSecondary: '#8E8E93',
    card: '#FFFFFF',
    shadow: 'rgba(0, 0, 0, 0.1)',
    welcomeBackground: '#A5D6A7', // Light green for welcome screen
    chart: {
      blue: accentColor,
      green: primaryGreen,
      yellow: '#FFCC00',
      orange: '#FF9500',
      red: '#FF3B30',
    },
    chartBlue: accentColor,
    chartGreen: primaryGreen,
    chartYellow: '#FFCC00',
    chartOrange: '#FF9500',
    chartRed: '#FF3B30',
    gray: '#8E8E93',
  },
  dark: {
    text: '#fff',
    background: '#121212',
    tint: primaryGreenLight,
    tabIconDefault: '#ccc',
    tabIconSelected: primaryGreenLight,
    primary: primaryGreenLight,
    primaryLight: primaryGreen,
    secondary: '#1C1C1E',
    secondaryLight: '#2C2C2E',
    accent: '#64B5F6',
    success: '#32D74B',
    error: '#FF453A',
    warning: '#FFD60A',
    border: '#38383A',
    textSecondary: '#8E8E93',
    card: '#1E1E1E',
    shadow: 'rgba(0, 0, 0, 0.3)',
    welcomeBackground: '#2E7D32', // Dark green for welcome screen
    chart: {
      blue: '#64B5F6',
      green: primaryGreenLight,
      yellow: '#FFD60A',
      orange: '#FF9F0A',
      red: '#FF453A',
    },
    chartBlue: '#64B5F6',
    chartGreen: primaryGreenLight,
    chartYellow: '#FFD60A',
    chartOrange: '#FF9F0A',
    chartRed: '#FF453A',
    gray: '#8E8E93',
  },
};
