const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#1E5631',
    primaryLight: '#8BC34A',
    secondary: '#8BC34A',
    secondaryLight: '#DCEDC8',
    accent: '#4CAF50',
    error: '#D32F2F',
    warning: '#FFA000',
    info: '#1976D2',
    success: '#388E3C',
    card: '#FFFFFF',
    border: '#E0E0E0',
    notification: '#FF4081',
    placeholder: '#9E9E9E',
    disabled: '#BDBDBD',
    chartGreen: '#4CAF50',
    chartRed: '#F44336',
  },
  dark: {
    text: '#fff',
    background: '#121212',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primary: '#8BC34A',
    primaryLight: '#DCEDC8',
    secondary: '#4CAF50',
    secondaryLight: '#A5D6A7',
    accent: '#69F0AE',
    error: '#FF5252',
    warning: '#FFD740',
    info: '#40C4FF',
    success: '#69F0AE',
    card: '#1E1E1E',
    border: '#2C2C2C',
    notification: '#FF4081',
    placeholder: '#757575',
    disabled: '#424242',
    chartGreen: '#69F0AE',
    chartRed: '#FF5252',
  },
};
