const tintColorLight = '#2E7DAF';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#2E7DAF',
    primaryLight: '#5BA3D0',
    secondary: '#F5F8FA',
    secondaryLight: '#EDF2F7',
    accent: '#FF9500',
    success: '#4CD964',
    error: '#FF3B30',
    warning: '#FFCC00',
    border: '#E1E1E1',
    textSecondary: '#8E8E93',
    card: '#FFFFFF',
    shadow: '#000000',
    chart: {
      blue: '#2E7DAF',
      green: '#4CD964',
      yellow: '#FFCC00',
      orange: '#FF9500',
      red: '#FF3B30',
    },
    chartBlue: '#2E7DAF',
    chartGreen: '#4CD964',
    chartYellow: '#FFCC00',
    chartOrange: '#FF9500',
    chartRed: '#FF3B30',
    gray: '#8E8E93',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primary: '#5BA3D0',
    primaryLight: '#8BBFE0',
    secondary: '#1C1C1E',
    secondaryLight: '#2C2C2E',
    accent: '#FF9F0A',
    success: '#32D74B',
    error: '#FF453A',
    warning: '#FFD60A',
    border: '#38383A',
    textSecondary: '#8E8E93',
    card: '#1C1C1E',
    shadow: '#000000',
    chart: {
      blue: '#5BA3D0',
      green: '#32D74B',
      yellow: '#FFD60A',
      orange: '#FF9F0A',
      red: '#FF453A',
    },
    chartBlue: '#5BA3D0',
    chartGreen: '#32D74B',
    chartYellow: '#FFD60A',
    chartOrange: '#FF9F0A',
    chartRed: '#FF453A',
    gray: '#8E8E93',
  },
};
